/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * DMA header for AMD CPM5 Queue-based DMA Subsystem variant
 *
 * Copyright (C) 2023, Advanced Micro Devices, Inc.
 */

#ifndef __QDMA_CPM5_H
#define __QDMA_CPM5_H

#include "qdma.h"

#define QDMA_PF_QUEUE_COUNT_REGOFF		0x120
#define QDMA_PF_RING_SIZE_REGOFF		0x204
#define QDMA_PF_CTXT_DATA_REGOFF		0x804
#define QDMA_PF_CTXT_MASK_REGOFF		0x824
#define QDMA_PF_CTXT_CMD_REGOFF			0x844
#define QDMA_PF_C2H_MM_CTRL_REGOFF		0x1004
#define QDMA_PF_H2C_MM_CTRL_REGOFF		0x1204

const struct qdma_reg_field qdma_regfs_cpm5[QDMA_REGF_MAX] = {
	[QDMA_REGF_IRQ_ENABLE] = QDMA_REGF(QDMA_REGO_CTXT_DATA, 53, 53),
	[QDMA_REGF_WBK_ENABLE] = QDMA_REGF(QDMA_REGO_CTXT_DATA, 52, 52),
	[QDMA_REGF_WBI_INTVL_ENABLE] = QDMA_REGF(QDMA_REGO_CTXT_DATA, 35, 35),
	[QDMA_REGF_QUEUE_ENABLE] = QDMA_REGF(QDMA_REGO_CTXT_DATA, 32, 32),
	[QDMA_REGF_QUEUE_MODE] = QDMA_REGF(QDMA_REGO_CTXT_DATA, 63, 63),
	[QDMA_REGF_DESC_BASE] = QDMA_REGF_ULL(QDMA_REGO_CTXT_DATA, 127, 64),
	[QDMA_REGF_DESC_SIZE] = QDMA_REGF(QDMA_REGO_CTXT_DATA, 49, 48),
	[QDMA_REGF_RING_ID] = QDMA_REGF(QDMA_REGO_CTXT_DATA, 47, 44),
	[QDMA_REGF_CMD_INDX] = QDMA_REGF(QDMA_REGO_CTXT_CMD, 19, 7),
	[QDMA_REGF_CMD_CMD] = QDMA_REGF(QDMA_REGO_CTXT_CMD, 6, 5),
	[QDMA_REGF_CMD_TYPE] = QDMA_REGF(QDMA_REGO_CTXT_CMD, 4, 1),
	[QDMA_REGF_CMD_BUSY] = QDMA_REGF(QDMA_REGO_CTXT_CMD, 0, 0),
	[QDMA_REGF_MM_H2C_CTRL] = QDMA_REGF(QDMA_REGO_MM_H2C_CTRL, 0, 0),
	[QDMA_REGF_MM_C2H_CTRL] = QDMA_REGF(QDMA_REGO_MM_C2H_CTRL, 0, 0),
	[QDMA_REGF_QUEUE_COUNT] = QDMA_REGF(QDMA_REGO_QUEUE_COUNT, 11, 0),
	[QDMA_REGF_RING_SIZE] = QDMA_REGF(QDMA_REGO_RING_SIZE, 15, 0),
};

const struct qdma_reg_off qdma_regos_cpm5[QDMA_REGO_MAX] = {
	[QDMA_REGO_CTXT_DATA] = QDMA_REGO(QDMA_PF_CTXT_DATA_REGOFF, 8),
	[QDMA_REGO_CTXT_CMD] = QDMA_REGO(QDMA_PF_CTXT_CMD_REGOFF, 1),
	[QDMA_REGO_CTXT_MASK] = QDMA_REGO(QDMA_PF_CTXT_MASK_REGOFF, 8),
	[QDMA_REGO_MM_H2C_CTRL] = QDMA_REGO(QDMA_PF_H2C_MM_CTRL_REGOFF, 2),
	[QDMA_REGO_MM_C2H_CTRL] = QDMA_REGO(QDMA_PF_C2H_MM_CTRL_REGOFF, 2),
	[QDMA_REGO_QUEUE_COUNT] = QDMA_REGO(QDMA_PF_QUEUE_COUNT_REGOFF, 1),
	[QDMA_REGO_RING_SIZE] = QDMA_REGO(QDMA_PF_RING_SIZE_REGOFF, 16),
};

#endif	/* __QDMA_CPM5_H */
